"""create_products_table

Revision ID: 9d6aa7229f3c
Revises: 0dfef06b7ef3
Create Date: 2026-02-13 00:49:50.941267

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9d6aa7229f3c"
down_revision: Union[str, Sequence[str], None] = "0dfef06b7ef3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
